plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/piotrmatejuk/Desktop/Aplikacje/Cien/cien-pwa"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]