[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[[redirects]]
  from = "/pb/*"
  to = "https://klauzule.tail4676a1.ts.net/cien-pb/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/regulamin"
  to = "/regulamin.html"
  status = 200

[[redirects]]
  from = "/polityka-prywatnosci"
  to = "/polityka-prywatnosci.html"
  status = 200

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
